### ISSUE TITLE
createQldbWriter seems to make a broke IonObject

### ISSUE THREAD

**Issue by karlos-oliveira** [awslabs/amazon-qldb-driver-nodejs#10]
I'm following [this sample](https://docs.aws.amazon.com/qldb/latest/developerguide/getting-started.nodejs.step-3.html) and the method bellow don't work, this is because "**createQldbWriter()**" method make a malformed ION object for some reason... 

This don't work
```
import { createQldbWriter } from "amazon-qldb-driver-nodejs";

..
..

export async function insertDocument(
    txn: TransactionExecutor,
    tableName: string,
    documents: object[]
): Promise<Result> {
    const statement: string = `INSERT INTO ${tableName} ?`;
    const documentsWriter: QldbWriter = createQldbWriter();
    writeValueAsIon(documents, documentsWriter);
    let result: Result = await txn.executeInline(statement, [documentsWriter]);
    return result;
}
```

This Work

```
import { makeTextWriter } from "ion-js";

..
..


export async function insertDocument(
    txn: TransactionExecutor,
    tableName: string,
    documents: object[]
): Promise<Result> {
    const statement: string = `INSERT INTO ${tableName} ?`;
    const documentsWriter: QldbWriter = makeTextWriter();
    writeValueAsIon(documents, documentsWriter);
    let result: Result = await txn.executeInline(statement, [documentsWriter]);
    return result;
}
```

Steps to reproduce ([in this scope](https://docs.aws.amazon.com/qldb/latest/developerguide/getting-started.nodejs.step-3.html)):

Work: 

```
const documentsWriter = makeTextWriter();

documentsWriter.stepIn(IonTypes.STRUCT);
documentsWriter.writeFieldName("hello")
documentsWriter.writeString("world")
documentsWriter.stepOut();
documentsWriter.close()
console.log(String.fromCharCode.apply(null, documentsWriter.getBytes())); 
```
Result

`{hello:"world"}`

Don't Work

```
const documentsWriter = createQldbWriter();

documentsWriter.stepIn(IonTypes.STRUCT);
documentsWriter.writeFieldName("hello")
documentsWriter.writeString("world")
documentsWriter.stepOut();
documentsWriter.close()
console.log(String.fromCharCode.apply(null, documentsWriter.getBytes())); 
```

Result
```
à êëØ¶
hello×
world
à êëØ¶
hello×
world
```

**Comment by othonrsanchez** [comment]
Hey @karlos-oliveira , thanks for reaching out.

The qldb driver uses Amazon Ion to represent the data. Ion provides *writers* to convert the data to Ion. The nodejs tutorial uses the IonBinaryWriter, that's why the output look like scrambled characters. There are other 2 writers like the IonTextWriter that you picked and the IonPrettyTextWriter. I found them on the ion-js repo: https://github.com/amzn/ion-js/tree/master/src

You can find more information about how to use Ion in the Ion Cookbook http://amzn.github.io/ion-docs/guides/cookbook.html

**Comment by othonrsanchez** [comment]
Let us know if you still have questions. Closing the issue.
