### ISSUE TITLE
Cannot use result or result list getters with v1.0.0-rc.1 

### ISSUE THREAD

**Issue by edwards-will** [awslabs/amazon-qldb-driver-nodejs#31]
Using the following code in javascript gives an error: 

> TypeError: resultList.get is not a function

```
const resultList = await txn.execute(`SELECT name FROM People WHERE name = Foo`);
const result = resultList.get(0);
```
This code was taken from the release note typescript examples in [Release v1.0.0-rc.1 of the Amazon QLDB Driver for Node JS](https://github.com/awslabs/amazon-qldb-driver-nodejs/releases).

Thanks

**Comment by yohanmartin** [comment]
There were two inaccuracies in the sample code given in release notes. [Both of them are corrected now](https://github.com/awslabs/amazon-qldb-driver-nodejs/releases)

1. `txn.execute()` always returns a [Result](https://github.com/awslabs/amazon-qldb-driver-nodejs/blob/v1.0.0-rc.1/src/Result.ts),  and you have to do `.getResultList()` to get an Array of `dom.Value`. 

2. Grab the first record using `resultList[0]`

Thank You for bringing this up and apologies for the inconvenience. Let me know if the issue persists.

**Comment by edwards-will** [comment]
The updated documentation with the use of `.getResultList()` resolved my issue, thanks!
