### ISSUE TITLE
JSON.stringify does not give exactly the right results on result list with v1.0.0-rc.1

### ISSUE THREAD

**Issue by edwards-will** [awslabs/amazon-qldb-driver-nodejs#32]
In the changelog for this release it mentions:

> results returned by execute and executeAndStreamResults can be converted into JSON String via JSON.stringify(result)

However this:
```
const resultList = await txn.execute(`SELECT name FROM People WHERE name = Foo`);
console.log(JSON.stringify(resultList));
```
Gives the result:
```{"_resultList":[{"name":"Foo"}]}```

I expected:
```
[{"name":"Foo"}]
```
Is the object with '_resultList' the correct result?

**Comment by yohanmartin** [comment]
The `txn.execute()` method will return a [Result](https://github.com/awslabs/amazon-qldb-driver-nodejs/blob/v1.0.0-rc.1/src/Result.ts). Then, grab the "resultList" using `getResultList()` method and pass it to `JSON.stringify()`

```
 const result = await txn.execute(`SELECT name FROM People WHERE name = Foo`);
const resultList = result.getResultList();
console.log(JSON.stringify(resultList));
```
The above code should give you the expected result
```
[{"name":"Foo"}]
```

I am sorry that the `getResultList()` method was not present in the sample of release notes. [The release notes are updated](https://github.com/awslabs/amazon-qldb-driver-nodejs/releases/tag/v1.0.0-rc.1)

Let us know if the issue persists.

Thank You.

**Comment by edwards-will** [comment]
The updated documentation with the use of `.getResultList()` resolved my issue, thanks!
