### ISSUE TITLE
How to join with document id as a foreign key?

### ISSUE THREAD

**Issue by nareshbhatia** [awslabs/amazon-qldb-driver-nodejs#42]
I have two tables:

1. Account
2. CashBalance

Account can have many Cash Balances (one of each currency). Hence I am storing the document Id of an `Account` as a foreign key inside `CashBalance` records. How do I join the CashBalance table with the Account table using the foreign key? I tried the following but it gives an empty result:

```
SELECT * FROM CashBalance AS c INNER JOIN Account AS a BY accountId ON c.accountId = a.accountId
```

Instead I have to break the query into two:

```
SELECT * FROM Account AS a BY accountId WHERE a.owner = ?
```

The above query gives me 1 accountId, which I can use to get CashBalance records:

```
SELECT * FROM CashBalance AS c WHERE c.accountId = ?
```

However this is not very convenient. Is there a better way?

P.S. All the join examples I have found so far are joining on non-id elements, e.g.

```
SELECT Vehicle FROM Vehicle INNER JOIN VehicleRegistration AS r
ON Vehicle.VIN = r.VIN WHERE r.Owners.PrimaryOwner.PersonId = ?
```

**Comment by saumehta9** [comment]
Hi @nareshbhatia, 

Can you try the following

`SELECT * FROM CashBalance AS c INNER JOIN Account AS a BY accountId ON c.accountId = accountId`

Thanks, 
Saurabh

**Comment by nareshbhatia** [comment]
That worked, @saumehta9 - thank you! Would be good to put one such example in the docs.
