### ISSUE TITLE
Update to ION-JS 5.0

### ISSUE THREAD

**Issue by mkhraisha** [awslabs/amazon-qldb-driver-nodejs#428]
https://github.com/amazon-ion/ion-js/releases/tag/v5.0.0 was released two weeks ago

**Comment by mkhraisha** [comment]
Has there been any movement on this?
This package still depends on  v4.3 https://github.com/awslabs/amazon-qldb-driver-nodejs/blob/6459be68bf203303598f8d907f713d94c8f6baca/package.json#L44

**Comment by mkhraisha** [comment]
Not sure who is responsible for maintaining this package, but there appear to be a number of outdated dependencies.

Last PR was merged by @allimn, so i'm pinging hopefully you'll know who to contact

**Comment by trstephen-amazon** [comment]
Sorry for the delay @mkhraisha ! Version 3.1.0 of the driver with an updated peer dependency on `ion-js` will be published to npm shortly.

**Comment by mkhraisha** [comment]
Awesome! 

Thank you.
