### ISSUE TITLE
Select with parameters doesn't work

### ISSUE THREAD

**Issue by Petah** [awslabs/amazon-qldb-driver-nodejs#45]
Hi, I'm probably doing something basic wrong here but I can't seem to get a `SELECT` statement to work with parameters:

```
const { QldbDriver } = require('amazon-qldb-driver-nodejs');

const driver = new QldbDriver('test', {
    region: 'us-east-1'
});

driver.executeLambda(async (transaction) => {
    // await transaction.execute('DROP TABLE test');
    await transaction.execute('CREATE TABLE test');
    await transaction.execute('INSERT INTO test VALUE ?', {
        foo: 'bar',
    });
    const result1 = await transaction.execute('SELECT * FROM test WHERE foo = ?', ['bar']);
    console.log(result1.getResultList().length);
    const result2 = await transaction.execute('SELECT * FROM test WHERE foo = \'bar\'');
    console.log(result2.getResultList().length);
});
```

Ouptut:
```
0
1
```

Running version `^2.0.0-rc.1`

**Comment by yohanmartin** [comment]
Thank you @Petah for reaching out and sorry for the delayed response.

 From what I see, you might just want to do

```
const result = await transaction.execute('SELECT * FROM test WHERE foo = ?', 'bar');
```

The preview version of the Node.js driver required the parameters to be in an array, but all versions after release [v1.0.0-rc.1](https://github.com/awslabs/amazon-qldb-driver-nodejs/releases/tag/v1.0.0-rc.1) support passing variable number of parameters. The issue #23 captures the before and after experience of passing the parameters to the query.

Does this capture your use-case correctly and answer your question?

Thank You.

**Comment by aurghob33** [comment]
Hi @Petah, 
Since there were no further questions and it has been quite some time since we answered the question, I am closing this issue.
If it seems that the issue was closed in error, please feel free to reopen this issue or create a new issue with us and we will look into any further questions or issues.

Thanks You.
