### ISSUE TITLE
Unexpected query result

### ISSUE THREAD

**Issue by vnea** [awslabs/amazon-qldb-driver-nodejs#5]
Hello,

I have a QLDB table named **Songs**.

I wrote this simple lambda to get the first song :
```typescript
export const getFirstSong = async () => {
  const qldbSession = await getQldbDriver().getSession();

  const songs = await qldbSession.executeStatement('SELECT * FROM Songs', []);

  return {
    body: JSON.stringify(songs.getResultList()[0])
  };
};
```

But then I have this as a result :
```json
{
  "_annotations": null,
  "_parser": {
    "_raw_type": -1,
    "_len": -1,
    "_null": false,
    "_fid": -1,
    "_as": -1,
    "_ae": -1,
    "_a": [],
    "_ts": [
      20
    ],
    "_in_struct": false,
    "_in": {
      "_type": 1,
      "_src": {
        "0": 224,
        "1": 1,
        "2": 0,
        "3": 234,
        "4": 234,
        "5": 129,
        "6": 131,
        "7": 215,
        "8": 135,
        "9": 181,
        "10": 132,
        "11": 78,
        "12": 97,
        "13": 109,
        "14": 101,
        "15": 214,
        "16": 138,
        "17": 132,
        "18": 116,
        "19": 111,
        "20": 116,
        "21": 111
      },
      "_limit": 22,
      "_start": 0,
      "_pos": 0
    }
  },
  "_cat": {
    "symbolTables": {
      "$ion": [
        null,
        {
          "_name": "$ion",
          "_version": 1,
          "_symbols": [
            "$ion",
            "$ion_1_0",
            "$ion_symbol_table",
            "name",
            "version",
            "imports",
            "symbols",
            "max_id",
            "$ion_shared_symbol_table"
          ],
          "_idsByText": {
            "$ion_shared_symbol_table": 8,
            "max_id": 7,
            "symbols": 6,
            "imports": 5,
            "version": 4,
            "name": 3,
            "$ion_symbol_table": 2,
            "$ion_1_0": 1,
            "$ion": 0
          },
          "_numberOfSymbols": 9
        }
      ]
    }
  },
  "_symtab": {
    "_import": {
      "_parent": null,
      "_symbolTable": {
        "_name": "$ion",
        "_version": 1,
        "_symbols": [
          "$ion",
          "$ion_1_0",
          "$ion_symbol_table",
          "name",
          "version",
          "imports",
          "symbols",
          "max_id",
          "$ion_shared_symbol_table"
        ],
        "_idsByText": {
          "$ion_shared_symbol_table": 8,
          "max_id": 7,
          "symbols": 6,
          "imports": 5,
          "version": 4,
          "name": 3,
          "$ion_symbol_table": 2,
          "$ion_1_0": 1,
          "$ion": 0
        },
        "_numberOfSymbols": 9
      },
      "_offset": 1,
      "_length": 9
    },
    "index": {},
    "_symbols": [],
    "offset": 10
  },
  "_raw_type": -2
}
```

I don't really understand how to get the real data from this JSON.
It seems it uses **ion** but I'm not familiar with this.

Commit used :
**05361d5d** Daniel E Knudsen <knudsd@amazon.com> on 12/11/2019 at 02:47

**Comment by marcbowes** [comment]
Hi @vnea,

I think you opened this issue before the sample application was released so you probably haven't had a chance to look through the examples, e.g. https://github.com/aws-samples/amazon-qldb-dmv-sample-nodejs/blob/master/src/ScanTable.ts

In QLDB, your documents are stored in [Ion](http://amzn.github.io/ion-docs/). So, you need to use the APIs defined in the [Ion-js](https://github.com/amzn/ion-js) library. The above example uses a pretty printer to print out each record.

**Comment by mdhama** [comment]
Hi @marcbowes 
How to get data in JSON Object?

**Comment by vladaman** [comment]
I am adding my 2 cents too! **I'd like to see output as JSON Object.** All your other DBs work with JSON and suddenly you decided to move to ion. Probably there are reasons to do so, yet this seems like extra over-engineering. Having simple API for insert/update/select would be great without need of going through the ion parsing. Especially since this is javascript library/driver.
This complexity scares me away and so far we are sticking to DynamoDB which has nicer API we think. We'd love to use QLDB for some other use cases but only if it's simple.

**Comment by saumehta9** [comment]
Hi @vnea, @mdhama, @vnea @vladaman

The objects returned by the driver interfaces are not plain javascript objects, they are in-fact ION objects.
Amazon Ion is a richly-typed, self-describing, hierarchical data serialization format offering interchangeable binary and text representations. More details here - http://amzn.github.io/ion-docs/. I really recommend going through the ion documents and gain familiarity.

We understand that extracting values from javascript ion objects is not very straightforward.
We have opened an [Issue](https://github.com/amzn/ion-js/issues/531) on Ion to possibly come up with something simpler. 

I have written a small snippet that demonstrates how to extract values from an ION object.

Sample Documents (The following is just a representation. The response returned by qldb driver is not a json string but an ION object)
> // Document 1
> {
> VIN: "1HVBBAANXWH544237",
> Type: "Semi",
> Year: 2009,
> Make: "Ford",
> Model: "F 150",
> Color: "Black"
> }
>
> // Document 2
> {
> VIN: "3HGGK5G53FM761765",
> Type: "Motorcycle",
> Year: 2011,
> Make: "Ducati",
> Model: "Monster 1200",
> Color: "Yellow"
> }
>

```
/*************************PRINTING DOCUMENTS*****************************************/

const qldbSession = await getQldbDriver().getSession();

const vehicles = await qldbSession.executeStatement('SELECT * FROM Vehicle', []);

const documents = vehicles.getResultList();

/*************************GET THE FIRST DOCUMENT*****************************************/

const document = documents[0]; //Document 1

document.next();

document.type(); //prints struct

document.stepIn(); // step into the struct

document.next(); //move pointer to the first field.

console.log(document.type()); //print string, yopu are on the first field.

console.log(document.fieldName()); //prints "VIN"
console.log(document.stringValue()); // prints "1HVBBAANXWH544237"

document.next(); //move pointer to the second field.

console.log(document.type()); //print string, you are on the first field.

console.log(document.fieldName()); //prints "Type"
console.log(document.stringValue()); // prints "Semi"

/*************************GET THE SECOND DOCUMENT*****************************************/

const document = documents[1]; //Document 2

document.next();

document.type(); //prints struct

document.stepIn(); // step into the struct

document.next(); //move pointer to the first field.

console.log(document.type()); //print string, yopu are on the first field.

console.log(document.fieldName()); //prints "VIN"
console.log(document.stringValue()); // prints "3HGGK5G53FM761765"

document.next(); //move pointer to the second field.

console.log(document.type()); //print string, you are on the first field.

console.log(document.fieldName()); //prints "Type"
console.log(document.stringValue()); // prints "Motorcycle"

/*****************************************END*****************************************/
```

Also we have a cookbook http://amzn.github.io/ion-docs/guides/cookbook.html.
This cookbook provides code samples for some simple Amazon Ion use cases.

More on reading ION documents here - http://amzn.github.io/ion-docs/guides/cookbook.html#reading-and-writing-ion-data

**Comment by marcbowes** [comment]
@vladaman

> I am adding my 2 cents too! **I'd like to see output as JSON Object.** 

Thanks for your feedback.

We understand that the current interface is far from ideal. That is one of the reasons we released this driver at 0.1.

Ion in other languages (e.g. Java) supports downmapping to JSON. Once we have that in the Node.js implementation, it should be simple to map the object into JSON and continue, or even build an abstraction that always does that. Would that meet your requirements?

> This complexity scares me away and so far we are sticking to DynamoDB which has nicer API we think. We'd love to use QLDB for some other use cases but only if it's simple.

I hear you. Please watch this issue for progress on the Ion APIs. I think we can get it to a point where Ion is not the deciding factor.

**Comment by KotoJallow** [comment]
@vladaman @marcbowes 
I had the same issue (Ion to JSON) and solved it in my project. However, seeing your Issue I put a solution on Github https://github.com/KotoJallow/IonToJson.git this might help. It converts result.getResultList()
to a Javascript Object (JSON)... test files on Github too.
I hope this helps

**Comment by KotoJallow** [comment]
@vladaman @marcbowes 
Managed to publish the package
npm install ion-to-json
Sample usage on Github ReadMe.
Viola

**Comment by yohanmartin** [comment]
Hello @vladaman @mdhama @vnea,
How about giving [release v1.0.0-rc.1](https://github.com/awslabs/amazon-qldb-driver-nodejs/releases/tag/v1.0.0-rc.1) a try? We have added new features which, we hope, will simplify result processing.

You can use the samples in [Release notes](https://github.com/awslabs/amazon-qldb-driver-nodejs/releases/tag/v1.0.0-rc.1) to check the new experience.
To see full list of changes, please refer to the [CHANGELOG](https://github.com/awslabs/amazon-qldb-driver-nodejs/blob/v1.0.0-rc.1/CHANGELOG.md).

Thank You.

**Comment by saumehta9** [comment]
As yohanmartin mentioned, we have made improvements to our APIs in the v1 and v2 of the drivers. I would suggest you to upgrade to the latest version. Please reopen if you still face any issues.
