### ISSUE TITLE
How do I prepare SQL query to escape special characters to prevent SQL injection?

### ISSUE THREAD

**Issue by JacekSmolakFandom** [awslabs/amazon-qldb-driver-nodejs#50]
The method `execute` simply takes the query, but I can't find any `escape` or params preparation utility (e.g. via placeholders).

How do I make sure that the query that is dynamically constructed is escaped so that SQL injection is not possible?

**Comment by yohanmartin** [comment]
Thank you for reaching out and sorry for the delay in response.

Amazon QLDB Driver for NodeJs supports parameterized queries.  Here is an excerpt from [quick start tutorial](https://docs.aws.amazon.com/qldb/latest/developerguide/driver-quickstart-nodejs.html)

```
  const person = {firstName: "John", lastName: "Doe", age: 42}
  driver.executeLambda((txn) => {
    txn.execute("INSERT INTO People ?", person);
  })
```

Or to read the document

```
  driver.executeLambda(async (txn) => {
    return txn.execute("SELECT firstName, age, lastName FROM People WHERE firstName = ?", "John")
  })
```

You can look into the [quick start](https://docs.aws.amazon.com/qldb/latest/developerguide/driver-quickstart-nodejs.html) or the [sample app](https://docs.aws.amazon.com/qldb/latest/developerguide/getting-started.nodejs.tutorial.html) tutorials for more examples of parameterized queries.

Hope this helps.

**Comment by JacekSmolakFandom** [comment]
Thanks! That is exactly what I was looking for.

I asked as used to looking into tests as a documentation, I could not find a well prepared example (query in test is not parametrised). Perhaps it would be good to provide examples for single and multiple parameters you can set :v:

**Comment by yohanmartin** [comment]
Thank you for the great feedback. We will work on providing examples on AWS docs and in the tests.
