### ISSUE TITLE
Missing dependency upon @aws-sdk/smithy-client and @aws-sdk/node-http-handler

### ISSUE THREAD

**Issue by belinde** [awslabs/amazon-qldb-driver-nodejs#534]
In `/dist/src/errors/Errors.d.ts` there's a `import { ServiceException } from "@aws-sdk/smithy-client";`, but that package is not listed in the dependencies. In addition, it has moved to @smithy/smithy-client. 

A similar issue is in `/dist/src/QldbDriver.d.ts`  with an import from @aws-sdk/node-http-handler that has moved to @smithy/node-http-handler

At the moment, the builds fail with a `Cannot find module '@aws-sdk/smithy-client' or its corresponding type declarations.` It must be noted that in my project @smithy/smithy-client is already installed by some other dependency.

**Comment by allimn** [comment]
Hi @belinde , it should be installed as part of @aws-sdk/client-qldb-session  and @aws-sdk/client-qldb. Please let me know if `npm install` doesn't install @aws-sdk/smithy-client as indirect dependency.

**Comment by allimn** [comment]
This will be resolved as part of new minor version release https://github.com/awslabs/amazon-qldb-driver-nodejs/pull/571

**Comment by ChrisSargent** [comment]
I can confirm this was fixed in that release.
