### ISSUE TITLE
Return ResultReadable from executeAndStreamResults(), instead of Readable

### ISSUE THREAD

**Issue by aasadsan** [awslabs/amazon-qldb-driver-nodejs#59]
Currently, unbuffered results are created as `ResultStream` instance (`class ResultStream extends Readable`), but [`executeAndStreamResults()`](https://github.com/awslabs/amazon-qldb-driver-nodejs/blob/master/src/TransactionExecutable.ts#L38) returns a [Readable](https://nodes.duniter.io/typescript/duniter/typedoc/classes/_stream_.internal.readable.html).

In 2.1.0, `ResultStream` can provide server-side statistics through [`getConsumedIOs()`](https://github.com/awslabs/amazon-qldb-driver-nodejs/blob/master/src/ResultStream.ts#L65) and [`getTimingInformation()`](https://github.com/awslabs/amazon-qldb-driver-nodejs/blob/master/src/ResultStream.ts#L75) methods.

We can change the return type of `executeAndStreamResults()` from `Readable` to `ResultStream` so the user can access the statistic methods. 
We can also rename `ResultStream` to `ResultReadable` to make it clear to the user, that the return type is still a Readable (since ResultReadable is extending Readable).
This change would be backward compatible.

**Comment by byronlin13** [comment]
This has been released in [v2.1.1](https://github.com/awslabs/amazon-qldb-driver-nodejs/releases/tag/2.1.1). For information on how to retrieve query stats via `ResultReadable` please go to [Getting Statement Statistics](https://docs.aws.amazon.com/qldb/latest/developerguide/working.statement-stats.html)
