### ISSUE TITLE
Deprecate RetryConfig

### ISSUE THREAD

**Issue by simonz-bq** [awslabs/amazon-qldb-driver-nodejs#70]
Mark RetryConfig and related functions/methods/types as deprecated, to be eventually removed in the next major release.

**Comment by kylepbit** [comment]
@alpian are you able to comment on the necessity of this change? There was some offline discussion which is not captured here for the benefit of the community (apologies all).

**Comment by alpian** [comment]
Looking at this, I'm no longer convinced this is the right thing to do. I think it should never be necessary to override the backoff strategy but the number of retries probably should be configurable. So I don't think we should deprecate the entire config object, maybe just the backoff strategy.

**Comment by kylepbit** [comment]
We have an object dedicated to the configuration of retries, and I tend to agree that the number of retries may be useful. I think the question is do we keep the config object with just the retry limit given that we foresee cases where additional options may be useful? My inclination would be to do just that, deprecate the retry strategy option in the config and keep the config object.

**Comment by simonz-bq** [comment]
Given what Kyle has said, that we shoud keep the Config in the case that we forsee additional options, I don't quite see the value in removing or deprecating BackoffStrategy.

It's an optional parameter so users can opt to completely ignore it. It's also come in handy in the past regarding testing or reproducing issues.

**Comment by alpian** [comment]
Sounds ok for the time being.
