### ISSUE TITLE
"Digests don't match" when encapsulating table name in quotation marks.

### ISSUE THREAD

**Issue by kueckermann** [awslabs/amazon-qldb-driver-nodejs#8]
**This Works:**
```javascript
const { PooledQldbDriver } = require("amazon-qldb-driver-nodejs");
const qldb = new PooledQldbDriver("test", {
    region: "us-east-1"
});
const session = await qldb.getSession();
await session.executeLambda(async (txn) => {
    await txn.executeInline(`INSERT INTO RandomTable VALUE {'test': 'hello world'}`)
})
```

When encapsulating the table name in quotation marks it will fail. Note that this works via the QLDB Query Editor but fails via driver.
**This Fails:**
```javascript
const { PooledQldbDriver } = require("amazon-qldb-driver-nodejs");
const qldb = new PooledQldbDriver("test", {
    region: "us-east-1"
});
const session = await qldb.getSession();
await session.executeLambda(async (txn) => {
    await txn.executeInline(`INSERT INTO "RandomTable" VALUE {'test': 'hello world'}`)
})
```

**Full error:**
```javascript
BadRequestException: Digests don't match
    at Request.extractError ( .... node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners ( .... node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit ( .... node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit ( .... node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition ( .... node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo ( .... node_modules/aws-sdk/lib/state_machine.js:14:12)
    at  .... node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> ( .... node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> ( .... node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners ( .... node_modules/aws-sdk/lib/sequential_executor.js:116:18
```

According to the docs this should still work to escape reserved words: https://docs.aws.amazon.com/qldb/latest/developerguide/ql-reference.reserved.html

This same errors occurs when the table name is a reserved word such as Transaction.
If Transaction is used as a table name and is not encapsulated in quotes then the error thrown will be: _BadRequestException: Parser Error: at line 1, column 13: Invalid path component, expecting either an IDENTIFIER or STAR, got: KEYWORD with value:_

**Comment by othonrsanchez** [comment]
Hi @kueckermann , Thanks for reaching out.

We are looking into the issue and we'll keep you posted.

**Comment by kueckermann** [comment]
Thanks @othonrsanchez, I did see recently in the docs not to use reserved words for table names. However was interesting to note that I didnt get issues with it from the AWS console but did from the driver.

**Comment by marcbowes** [comment]
@kueckermann that's because it's a bug in https://github.com/amzn/ion-hash-js. You're not doing anything wrong. We will get an issue open there and linked here.

**Comment by othonrsanchez** [comment]
We have identified the bug in the driver and we are working on the fix.
