### ISSUE TITLE
How to read results from executeStatement ?

### ISSUE THREAD

**Issue by vladaman** [awslabs/amazon-qldb-driver-nodejs#9]
Hi,

can you please include a tutorial how to read Binary Results as JSON? I have following:

```
    pooledQldbDriver.getSession().then(function(d) {
        d.executeStatement('select * from mytable').then(function(f) {
            f.getResultList().forEach(function(result, i){
                console.log(result);
            });
        });
    });
```

and it gives me
```
BinaryReader {
  _annotations: null,
  _parser: 
   ParserBinaryRaw {
     _raw_type: -1,
     _len: -1,
     _curr: undefined,
     _null: false,
     _fid: -1,
     _as: -1,
     _ae: -1,
     _a: [],
     _ts: [ 20 ],
     _in_struct: false,
     _in: BinarySpan { _type: 1, _src: [Object], _limit: 52, _start: 0, _pos: 0 } },
  _cat: Catalog { symbolTables: { '$ion': [Array] } },
  _symtab: 
   LocalSymbolTable {
     _import: Import { _parent: null, _symbolTable: [Object], _offset: 1, _length: 9 },
     index: {},
     _symbols: [],
     offset: 10 },
  _raw_type: -2 }
```

**Comment by saumehta9** [comment]
Hi @vladaman, Thanks for reaching out.

This should help you with reading the results. 
https://github.com/awslabs/amazon-qldb-driver-nodejs/issues/5#issuecomment-566253232

**Comment by karlos-oliveira** [comment]
@vladaman its not ideal, but i [made some methods](https://github.com/karlos-oliveira/qldb-auxiliar-methods/blob/master/lib/index.js) to help to parse the qldbResult to Json. There much to improve, but a believe that can help somehow.

**qldbResultToJson** is the main method in this file.

**Comment by aurghob33** [comment]
Hi,

Closing out the issue as it has been open and inactive for some time.
Please feel free to open a new issue or reopen this issue if you have more questions.
