### ISSUE TITLE
Session pool is empty. Please close existing sessions first before retrying.

### ISSUE THREAD

**Issue by vihuy** [awslabs/amazon-qldb-driver-nodejs#90]
Unhandled Rejection (SessionPoolEmptyError): Session pool is empty. Please close existing sessions first before retrying.
<img width="830" alt="Screen Shot 2021-05-27 at 4 30 08 PM" src="https://user-images.githubusercontent.com/26733094/119802662-ee161400-bf08-11eb-9f4f-560519ec7020.png">

I fixed the other error, but it reappears this error. Please help me.

**Comment by simonz-bq** [comment]
Hi @vihuy,

When constructing the driver, there is an option to set the maximum number of transactions as shown [on this line](https://github.com/awslabs/amazon-qldb-driver-nodejs/blob/966297af96c4bb36f2829c2c2f77962c360a5a9d/src/QldbDriver.ts#L81).

The error you're getting is caused by too many concurrent operations on the driver to QLDB. You can mitigate this by either waiting for some `execute` or `getTableName` methods to finish before starting more, or by increasing the parameter specifying the maximum number of concurrent transactions.

**Comment by vihuy** [comment]
> Hi @vihuy,
> 
> When constructing the driver, there is an option to set the maximum number of transactions as shown [on this line](https://github.com/awslabs/amazon-qldb-driver-nodejs/blob/966297af96c4bb36f2829c2c2f77962c360a5a9d/src/QldbDriver.ts#L81).
> 
> The error you're getting is caused by too many concurrent operations on the driver to QLDB. You can mitigate this by either waiting for some `execute` or `getTableName` methods to finish before starting more, or by increasing the parameter specifying the maximum number of concurrent transactions.

> I do not quite understand what you mean. Can you edit the code for me?

**Comment by simonz-bq** [comment]
```
let maxConcurrentTransactions = 100;
const qldbDriver: QldbDriver = new QldbDriver("promap", serviceConfigurationOptions, maxConcurrentTransactions);
```

**Comment by vihuy** [comment]
It shows another error that I don't know what? 
<img width="581" alt="Screen Shot 2021-05-31 at 3 17 08 PM" src="https://user-images.githubusercontent.com/26733094/120163225-7eaf6580-c223-11eb-8c02-d2a8666e8292.png">
<img width="1427" alt="Screen Shot 2021-05-31 at 3 16 24 PM" src="https://user-images.githubusercontent.com/26733094/120163233-8242ec80-c223-11eb-8cf3-2fb8fd0daed0.png">

**Comment by simonz-bq** [comment]
What environment are you running this on? The stack trace you posted appears to be a browser. The driver is currently designed to be a server-side library that runs only in a Node.js environment.

Can you post the rest of the stacktrace and more information about what you're using to run your code?

**Comment by vihuy** [comment]
I am using front end reactjs.
I installed aws-sdk but it doesn't have enough QLDBSession method when calling.
So I installed @aws-sdk/client-qldb-session to replace aws-sdk in package
Please give me some advice should I continue to use qldb for my technology of choice ?

**Comment by alpian** [comment]
Hi @vihuy, 

I am an engineer building QLDB. Unfortunately at the moment it is not possible to use this QLDB driver in a browser as it requires the Node runtime to execute which is not present in the browser context. We are aware of this limitation and are working to make a version of the JavaScript driver which can run in a browser.

The simplest way for you to use QLDB with JavsScript right now is to create a NodeJS Lambda on AWS and then talk to QLDB from that Lambda. After that you can use AWS API Gateway to communicate between your Lambda and your React front end in the browser.

I hope that helps, please let me know if you have any further questions :).

-Ian.

**Comment by HomayounA** [comment]
Hi @vihuy,

I wanted to reach out and see if there is anything on this issue that I can help you with. Please let me know if you need any clarification or you have any questions.

Homayoun.

**Comment by shuiwan** [comment]
We are working on the new JS driver, which can be used for browser scripts.

**Comment by allimn** [comment]
Hi @vihuy,

We have released a preview version of [JavaScript driver](https://github.com/awslabs/amazon-qldb-driver-js) which removes  any dependency on Node core modules. Typically you don't need to specify the maxConcurrentTransaction which has the default value of 6. 

Sample code snippet:
```
const qldbDriver: QldbDriver = new QldbDriver("testLedger", testServiceConfigOptions);
qldbDriver.getTableNames().then(function(tableNames: string[]) {
    console.log(tableNames);
});
```

Please give it a try and let us know if you have any questions. 

Ang
