### ISSUE TITLE
Excess time to process a query

### ISSUE THREAD

**Issue by mato777** [awslabs/amazon-qldb-driver-nodejs#92]
We run a job every day that process about 50k messages, and we see some of them taking more than 10 seconds to being processed.  Checking the traces, we see long `send command ` duration (about 9 seconds).  We have 3 consumers processing them, so it is about ~5 transaction per consumer per second.  Eact transaction takes an average of 200 ms to be processed.
The transaction makes about 10 queries and all the queries perform well, the same with the transaction when there is no heavy load.

Could this be related to maxConcurrentTransactions parameter?  We have the default that is 10 right now.

Trace image:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/10453322/156187949-77cc9eca-b490-4189-82b2-e7988d53e37c.png">

**Comment by allimn** [comment]
Hi, it's more expensive for server to process `StartSession` than other commands. If session pool is running out of the session permit, driver will send a `StartSession` command to create a new session to run transactions. So I'd suggest you expand the session pool by configuring the `maxConcurrentTransactions`. See [driver best practices](https://docs.aws.amazon.com/qldb/latest/developerguide/driver.best-practices.html) for reference.
