### ISSUE TITLE
Switch/Support of AWS SDK v3

### ISSUE THREAD

**Issue by kYem** [awslabs/amazon-qldb-driver-nodejs#93]
Hello,

Our team just done major upgrade for modular AWS SDK v3, that allow us not to pull in whole aws-sdk package, until we realised that this package have a peer dependency on it, and blocks us from removing aws-sdk all together.

Any plans from switching to aws-sdk v3 sub library packages? If so what would be the process, as I assume this would require a major change release?

**Comment by yasserf** [comment]
Hello,

I'm wondering if there is any release date on the horizon? The change to the v3 sdk is also on our critical path.

Thanks!

**Comment by allimn** [comment]
Hi, thanks for letting us know. We can't promise the release date but we are in the process of it.
